<a href="https://colab.research.google.com/github/Sayak-coder/SIH_26051/blob/main/indoor_temp_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

In [23]:
df=pd.read_csv('/content/trombe_wall_dataset_categorized.csv')
df.head()

,sample_id,time,hour,wall_thickness_L_m,thermal_conductivity_k_W_mK,volumetric_heat_capacity_rho_cp_MJ_m3K,thermal_resistance_R_val_m2K_W,trombe_air_cavity_gap_m,glazing_area_ratio_Ag,T_amb_Ladakh_C,G_total_Ladakh_Wm2,wind_Ladakh_ms,indoor_temperature_Tin_C,T_wall_ext_C,T_wall_mid_C,T_wall_int_C,material,best_structure
0,1,00:00:00,1,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-6.9238,0.0000,1.7189,Between 20 to 22,18.13,22.68,22.77,Stones,"Blocks (L=0.26m, Gap=0.10m, Ag=0.89)"
1,1,01:00:00,2,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-7.5383,0.0000,1.6852,Between 15 to 20,16.94,21.74,21.87,Stones,"Blocks (L=0.26m, Gap=0.10m, Ag=0.89)"
2,1,02:00:00,3,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-8.0913,0.0000,1.6439,Between 15 to 20,15.94,20.77,20.92,Stones,"Stones (L=0.30m, Gap=0.12m, Ag=0.87)"
3,1,03:00:00,4,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-8.6067,0.0000,1.6228,Between 15 to 20,15.17,19.79,19.96,Stones,"Stones (L=0.30m, Gap=0.12m, Ag=0.87)"
4,1,04:00:00,5,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-9.0898,0.0117,1.6169,Between 15 to 20,14.69,18.86,19.03,Stones,"Blocks (L=0.36m, Gap=0.15m, Ag=0.88)"

In [24]:
df=df.drop(['time','best_structure','material'],axis=1)
df.head()

,sample_id,hour,wall_thickness_L_m,thermal_conductivity_k_W_mK,volumetric_heat_capacity_rho_cp_MJ_m3K,thermal_resistance_R_val_m2K_W,trombe_air_cavity_gap_m,glazing_area_ratio_Ag,T_amb_Ladakh_C,G_total_Ladakh_Wm2,wind_Ladakh_ms,indoor_temperature_Tin_C,T_wall_ext_C,T_wall_mid_C,T_wall_int_C
0,1,1,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-6.9238,0.0000,1.7189,Between 20 to 22,18.13,22.68,22.77
1,1,2,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-7.5383,0.0000,1.6852,Between 15 to 20,16.94,21.74,21.87
2,1,3,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-8.0913,0.0000,1.6439,Between 15 to 20,15.94,20.77,20.92
3,1,4,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-8.6067,0.0000,1.6228,Between 15 to 20,15.17,19.79,19.96
4,1,5,0.2624,1.6869,1.4962,0.1555,0.0923,0.3832,-9.0898,0.0117,1.6169,Between 15 to 20,14.69,18.86,19.03

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sample_id                               12000 non-null  int64
 1   hour                                    12000 non-null  int64
 2   wall_thickness_L_m                      12000 non-null  float64
 3   thermal_conductivity_k_W_mK             12000 non-null  float64
 4   volumetric_heat_capacity_rho_cp_MJ_m3K  12000 non-null  float64
 5   thermal_resistance_R_val_m2K_W          12000 non-null  float64
 6   trombe_air_cavity_gap_m                 12000 non-null  float64
 7   glazing_area_ratio_Ag                   12000 non-null  float64
 8   T_amb_Ladakh_C                          12000 non-null  float64
 9   G_total_Ladakh_Wm2                      12000 non-null  float64
 10  wind_Ladakh_ms                          12000 non-null  float64
 11  indoor_temperature_Tin_C                12000 non-null  object
 12  T_wall_ext_C                            12000 non-null  float64
 13  T_wall_mid_C                            12000 non-null  float64
 14  T_wall_int_C                            12000 non-null  float64
dtypes: float64(12), int64(2), object(1)
memory usage: 1.4+ MB

In [26]:
print(df['indoor_temperature_Tin_C'].unique())

['Between 20 to 22' 'Between 15 to 20' 'Between 22 to 25' 'Above 25'
 'Below 15']

In [27]:
df['indoor_temperature_Tin_C']=df['indoor_temperature_Tin_C'].map({'Below 15':0,'Between 15 to 20':1,'Between 20 to 22':2,'Between 22 to 25':3,'Above 25':4})

In [28]:
print(df['indoor_temperature_Tin_C'].unique())

[2 1 3 4 0]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   sample_id                               12000 non-null  int64
 1   hour                                    12000 non-null  int64
 2   wall_thickness_L_m                      12000 non-null  float64
 3   thermal_conductivity_k_W_mK             12000 non-null  float64
 4   volumetric_heat_capacity_rho_cp_MJ_m3K  12000 non-null  float64
 5   thermal_resistance_R_val_m2K_W          12000 non-null  float64
 6   trombe_air_cavity_gap_m                 12000 non-null  float64
 7   glazing_area_ratio_Ag                   12000 non-null  float64
 8   T_amb_Ladakh_C                          12000 non-null  float64
 9   G_total_Ladakh_Wm2                      12000 non-null  float64
 10  wind_Ladakh_ms                          12000 non-null  float64
 11  indoor_temperature_Tin_C                12000 non-null  int64
 12  T_wall_ext_C                            12000 non-null  float64
 13  T_wall_mid_C                            12000 non-null  float64
 14  T_wall_int_C                            12000 non-null  float64
dtypes: float64(12), int64(3)
memory usage: 1.4 MB

In [30]:
from sklearn.model_selection import GroupShuffleSplit

X = df.drop(['indoor_temperature_Tin_C'], axis=1)
y = df['indoor_temperature_Tin_C']
groups = df['sample_id']   # keep this before you drop sample_id from X, or keep a copy

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=45)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns, index=X_test.index)

In [32]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
lrmodel=LinearRegression()
lrmodel.fit(X_train_scaled,y_train)
y_pred=lrmodel.predict(X_test_scaled)
print(mean_squared_error(y_test,y_pred))
print(lrmodel.score(X_test_scaled,y_test))

0.14937808916030665
0.8861223114835324

In [33]:
from xgboost import XGBClassifier
xgbmodel=XGBClassifier()
xgbmodel.fit(X_train_scaled,y_train)
y_pred=xgbmodel.predict(X_test_scaled)
print(mean_squared_error(y_test,y_pred))
print(xgbmodel.score(X_test_scaled,y_test))

0.04375
0.95625

### Predict Indoor Temperature with Custom Inputs

Now, let's use the trained XGBoost model to predict the `indoor_temperature_Tin_C` for custom input values. Make sure your input values are in a similar range to the data the model was trained on.

In [34]:
# Define custom input values as a dictionary
# These values should correspond to the columns in X, excluding 'indoor_temperature_Tin_C'
# Make sure to provide values for all 14 features:
# 'sample_id', 'hour', 'wall_thickness_L_m', 'thermal_conductivity_k_W_mK',
# 'volumetric_heat_capacity_rho_cp_MJ_m3K', 'thermal_resistance_R_val_m2K_W',
# 'trombe_air_cavity_gap_m', 'glazing_area_ratio_Ag', 'T_amb_Ladakh_C',
# 'G_total_Ladakh_Wm2', 'wind_Ladakh_ms', 'T_wall_ext_C', 'T_wall_mid_C', 'T_wall_int_C'

custom_input = {
    'sample_id': 1001,  # Example ID
    'hour': 10,         # Example hour
    'wall_thickness_L_m': 0.3, # Example wall thickness
    'thermal_conductivity_k_W_mK': 1.5, # Example thermal conductivity
    'volumetric_heat_capacity_rho_cp_MJ_m3K': 1.7, # Example volumetric heat capacity
    'thermal_resistance_R_val_m2K_W': 0.2, # Example thermal resistance
    'trombe_air_cavity_gap_m': 0.1, # Example trombe air cavity gap
    'glazing_area_ratio_Ag': 0.5, # Example glazing area ratio
    'T_amb_Ladakh_C': -5.0, # Example ambient temperature
    'G_total_Ladakh_Wm2': 150.0, # Example total solar radiation
    'wind_Ladakh_ms': 2.0, # Example wind speed
    'T_wall_ext_C': 10.0, # Example external wall temperature
    'T_wall_mid_C': 15.0, # Example middle wall temperature
    'T_wall_int_C': 18.0  # Example internal wall temperature
}

# Convert the custom input to a DataFrame
custom_df = pd.DataFrame([custom_input])

# Scale the custom input using the same scaler fitted on the training data
custom_input_scaled = pd.DataFrame(scaler.transform(custom_df), columns=custom_df.columns, index=custom_df.index)

# Predict the indoor temperature using the trained XGBoost model
predicted_indoor_temp_category = xgbmodel.predict(custom_input_scaled)

# The prediction is a category (0-4). You might want to map it back to original labels.
# Mapping: {'Below 15':0,'Between 15 to 20':1,'Between 20 to 22':2,'Between 22 to 25':3,'Above 25':4}

category_map = {
    0: 'Below 15',
    1: 'Between 15 to 20',
    2: 'Between 20 to 22',
    3: 'Between 22 to 25',
    4: 'Above 25'
}

predicted_label = [category_map[cat] for cat in predicted_indoor_temp_category]

print(f"Predicted indoor temperature category: {predicted_indoor_temp_category[0]}")
print(f"Predicted indoor temperature range: {predicted_label[0]}")

Predicted indoor temperature category: 1
Predicted indoor temperature range: Between 15 to 20